---
kind: pipeline
type: kubernetes
name: default
steps:
- name: restore cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    endpoint: http://192.168.0.112:9000
    root: drone
    restore: true
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY

- name: test
  image: harbor.xirion.net/library/elixir-rust:nightly # See Dockerfile.ci for the image definition
  commands:
    - cd nitrogen
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix test
    - cd ..

- name: rebuild cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    root: drone
    endpoint: http://192.168.0.112:9000
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
    rebuild: true
    mount:
      - nitrogen/deps
      - nitrogen/_build
      - target/
      - Cargo.lock
    when:
      event: push

services:
- name: postgres
  image: harbor.xirion.net/hub/library/postgres:13-alpine
  environment:
    POSTGRES_DB: nitrogen_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
